[debug] [2018-03-13T02:48:04.833Z] ----------------------------------------------------------------------
[debug] [2018-03-13T02:48:04.835Z] Command:       /usr/bin/node /usr/bin/firebase deploy
[debug] [2018-03-13T02:48:04.835Z] CLI Version:   3.17.6
[debug] [2018-03-13T02:48:04.835Z] Platform:      linux
[debug] [2018-03-13T02:48:04.835Z] Node Version:  v8.9.4
[debug] [2018-03-13T02:48:04.835Z] Time:          Mon Mar 12 2018 23:48:04 GMT-0300 (-03)
[debug] [2018-03-13T02:48:04.835Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-03-13T02:48:04.843Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-03-13T02:48:04.843Z] > authorizing via signed-in user
[debug] [2018-03-13T02:48:04.845Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/cademeudocinho-app  
  
 Mon Mar 12 2018 23:48:04 GMT-0300 (-03)
[debug] [2018-03-13T02:48:06.312Z] <<< HTTP RESPONSE 200
[debug] [2018-03-13T02:48:06.313Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/cademeudocinho-app/tokens  
  
 Mon Mar 12 2018 23:48:06 GMT-0300 (-03)
[debug] [2018-03-13T02:48:07.306Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'cademeudocinho-app'...
[info] 
[info] i  deploying hosting
[info] i  hosting: preparing dist directory for upload...
[debug] [2018-03-13T02:48:09.077Z] TypeError: no files or directories specified
    at Object.module.exports (/usr/lib/node_modules/firebase-tools/node_modules/tar/lib/create.js:20:11)
    at module.exports (/usr/lib/node_modules/firebase-tools/lib/prepareUpload.js:21:14)
    at module.exports (/usr/lib/node_modules/firebase-tools/lib/deploy/hosting/deploy.js:23:10)
    at _chain (/usr/lib/node_modules/firebase-tools/lib/deploy/index.js:23:45)
    at /usr/lib/node_modules/firebase-tools/lib/deploy/index.js:79:12
    at tryCatch (/usr/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/usr/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/usr/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/usr/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
[error] 
[error] Error: An unexpected error has occurred.
